### ISSUE TITLE
play / pause

### ISSUE THREAD

**Issue by g-a-v-i-n** [broskoski/mac.are.na#10]
I plan to implement this with a subheader that persists across views. It will have a play button and a current track time.

Eventually, this subheader will allow the user to nav away from the current playlist to browse other playlists while having control over playback and being able to return to the playlist of the current track.

**Comment by g-a-v-i-n** [comment]
I think I will hold off on a choo re-write for the time being :)

**Comment by broskoski** [comment]
Oo la la! Sounds great.

**Comment by g-a-v-i-n** [comment]
I think i might need to be authorized to push my branch
