### ISSUE TITLE
Fix bug in safari where song does not play audio

### ISSUE THREAD

**Issue by broskoski** [broskoski/mac.are.na#13]

**Comment by g-a-v-i-n** [comment]
my only lead on this is that it has something to do with localhost requesting from http vs ~~prod requesting from https~~ hmm wait prod also requests from http

**Comment by broskoski** [comment]
Actually think it might be something here: https://github.com/CookPete/react-player/issues/76

Though I did notice if this attribute https://github.com/broskoski/mac.are.na/blob/master/src/components/playlist_player.js#L25 is false it works fine in Safari.

**Comment by g-a-v-i-n** [comment]
Ok, that seemed to be causing the problem. I solved this by making the player visible and hiding it in it's style attr
