### ISSUE TITLE
Toggle visibility of unplayable blocks

### ISSUE THREAD

**Issue by hxrts** [broskoski/mac.are.na#42]
Just a visible/hidden toggle button. This [channel](http://mac.are.na/playlist/new-ugly-101) prompted the suggestion.

**Comment by callil** [comment]
I think by default unplayable blocks should be collapsed and say something like:
`10 unplayable blocks ▼`

**Comment by g-a-v-i-n** [comment]
this all sounds good to me

**Comment by g-a-v-i-n** [comment]
<img width="863" alt="screenshot 2018-02-09 13 41 24" src="https://user-images.githubusercontent.com/5265021/36043949-00e251da-0d9f-11e8-97dc-07142591ac38.png">
<img width="862" alt="screenshot 2018-02-09 13 41 30" src="https://user-images.githubusercontent.com/5265021/36043950-00f2e982-0d9f-11e8-8892-fd8b852f92c2.png">

thoughts?

**Comment by g-a-v-i-n** [comment]
done in https://github.com/broskoski/mac.are.na/pull/44
