### ISSUE TITLE
directly visiting a playlist via URL = 404

### ISSUE THREAD

**Issue by caseyg** [broskoski/mac.are.na#9]
To replicate:

1. paste `http://mac.are.na/playlist/what-i-think-is-sexy` into browser and hit enter
2. 404 Not Found (nginx)

❌ 

However, this works:

1. go to `http://mac.are.na`
2. click page 6
3. click `Casey Gollan / what i think is sexy!`

✅ 

Anyway, thank you — this is so awesome & useful. Just discovered it last week because somebody added my channel to the mac.arena channel!! (Not expecting a fix, just noting it here in case it's helpful.)

**Comment by broskoski** [comment]
Fixed, thanks!
